openapi: 3.0.0
info:
  title: Neurogenx API
  description: A simple API for a Neurogenx application.
  version: 1.0.0

servers:
  - url: https://neurogenx.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Development server

tags:
  - name: API Endpoints
    description: Core API endpoints for the Neurogenx application

paths:
  /:
    get:
      tags:
        - API Endpoints
      summary: Get API status
      description: Returns a success message to indicate the API is running.
      responses:
        '200':
          description: API is running successfully.
          content:
            text/plain:
              schema:
                type: string
                example: "Neurogenx API is running successfully!"
  
  /api/message:
    get:
      tags:
        - API Endpoints
      summary: Get a welcome message
      description: Returns a simple JSON message.
      responses:
        '200':
          description: A JSON message is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello from the Neurogenx API!"

  /api/submit:
    post:
      tags:
        - API Endpoints
      summary: Submit a message
      description: Accepts a user's name and message and returns a confirmation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Jane Doe"
                message:
                  type: string
                  example: "This is my first post request!"
      responses:
        '200':
          description: Message successfully received.
          content:
            application/json:
              schema:
                type: object
                properties:
                  confirmation:
                    type: string
                    example: "Hello Jane Doe, your message \"This is my first post request!\" has been received!"
        '400':
          description: Bad request. Name and message are required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Name and message are required."
  
  /api/messages:
    get:
      tags:
        - API Endpoints
      summary: Get all saved messages
      description: Retrieves a list of all messages stored in the database.
      responses:
        '200':
          description: A list of messages is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Jane Doe"
                    message:
                      type: string
                      example: "This is my first post request!"
                    date:
                      type: string
                      example: "2023-10-27T10:00:00.000Z"

